### ISSUE TITLE
Ошибка компиляции при использовании _Static_assert

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#107]
Получаю такую ошибку:

```
In file included from lib/rldb_plugin_file.c:23:0:
include/ejudge/runlog_state.h:68:57: error: expected ',' before ')' token
 _Static_assert(sizeof(struct user_run_header_info) == 64);

```
Действительно, согласно https://en.cppreference.com/w/c/language/_Static_assert
у _Static_assert один параметр предусмотрен только начиная с C++23, наверное,
пока рановато закладываться на использование стандарта C++23.

**Comment by blackav** [comment]
3.10.0 released
