### ISSUE TITLE
Неверная проверка номера строки в #line

### ISSUE THREAD

**Issue by kornevgen** [blackav/ejudge#115]
https://github.com/blackav/ejudge/blob/9ed575b361e3bcb87aa2d64a6431df3488e94b55/checkers/style_c.c#L162

Номер строки (значение переменной num) должен быть неотрицательным, а не только строго положительным ([пруф](https://gcc.gnu.org/onlinedocs/cpp/Line-Control.html)). Предлагается исправить <= на < в строке 162.

**Comment by blackav** [comment]
3.10.0 released
