### ISSUE TITLE
Просмотр исходного кода программы должен помечать комментарии к коду, как прочитанные

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#12]
Участник получил комментарий к коду, в результате у него есть комментарии в форме сообщения, отмеченные, как непрочитанные.

Если участник открыл исходный код страницы, то он увидел эти комментарии. Между тем сообщения продолжают висеть, как "непрочитанные".

Issue: просмотр исходного кода сабмита должен отмечать все комментарии к этому сабмиту, как прочитанные.

**Comment by blackav** [comment]
Fixed by 2a308e5a7fab17874261efa1a03c42fa09a3b5d0
