### ISSUE TITLE
Check Failed при параллельном тестировании с ejudge-agent

### ISSUE THREAD

**Issue by perveevm** [blackav/ejudge#127]
При тестировании **интерактивных** задач, а также задач типа **text-answer** происходит Check Failed на всех тестах при использовании ejudge-agent. Возможно, проблема присутствует и для других "нестандартных" типов задач, но я этого не проверял.

Пример того, как выглядит ошибка: `FAIL Answer file not found: "/home/judges/000264/problems/***/tests/01.a"`

При этом, если смонтировать `/home/judges` с основного сервера на проверяющую машину, ошибка не возникает

**Comment by blackav** [comment]
fixed in b3a4f1b0ad253fca15e48cc452060ab4a1d4e00d
