### ISSUE TITLE
Telegram-плагин: ошибка при сохранении информации о пользователях с 4-байтовыми символами в имени.

### ISSUE THREAD

**Issue by vvd170501** [blackav/ejudge#131]
Версия ejudge: пропатченная 3.10.0, b25655c039f84b1969142f5aafb60049de3bc645.

Если в имени/фамилии пользователя есть символы, которые в UTF-8 кодируются 4 байтами, то при записи в таблицы `telegram_users` и `telegram_chats` происходит ошибка (т.к. для этих таблиц используется charset utf8, а не utf8mb4).
Пример для пользователя с символом "🟥" в имени:

```
mysql: INSERT INTO telegram_users SET id = <...>, username = '...', first_name = '<F0><9F><9F><A5>', last_name = NULL ON DUPLICATE KEY UPDATE username = '...', first_name = '<F0><9F><9F><A5>', last_name = NULL;
2023-01-03T19:12:05Z:error:database error: Incorrect string value: '\xF0\x9F\x9F\xA5' for column `ejudge`.`telegram_users`.`first_name` at row 1
...
2023-01-03T19:12:05Z:info:updating chat info for <...>
mysql: INSERT INTO telegram_chats SET id = <...>, chat_type = 'private', title = NULL, username = '...', first_name = '<F0><9F><9F><A5>', last_name = NULL ON DUPLICATE KEY UPDATE chat_type = 'private', title = NULL, username = '...', first_name = '<F0><9F><9F><A5>', last_name = NULL;
2023-01-03T19:12:05Z:error:database error: Incorrect string value: '\xF0\x9F\x9F\xA5' for column `ejudge`.`telegram_chats`.`first_name` at row 1
```

При этом:
1. Строки с id пользователя всё равно создаются в обеих таблицах, но во все колонки, кроме id, записывается NULL.
2. Пользователь может подписаться и получать уведомления об изменении статуса посылок, т.е. эти ошибки не ломают механизм подписок.

**Comment by blackav** [comment]
Что с этим делать? Менять charset в таблицах?

**Comment by vvd170501** [comment]
> Что с этим делать? Менять charset в таблицах?

Да, вроде других вариантов нет.

**Comment by vvd170501** [comment]
А зачем вообще хранить имена? Они сейчас где-то используются?

**Comment by blackav** [comment]
Так дело не в этой таблице, а вообще. Если utf8 в mariadb не умеет в 4-байтный UTF-8, то это надо во всех таблицах менять.

**Comment by vvd170501** [comment]
> Если utf8 в mariadb не умеет в 4-байтный UTF-8, то это надо во всех таблицах менять.

Да, наверное, лучше поменять во всех таблицах.

Но похоже, что этого недостаточно. Попробовал поменять charset конкретно у таблиц для телеграма (https://github.com/vvd170501/ejudge/commit/5fa4fe90a600e9f0065ad282d045487115fa36ce), пересоздал все таблицы, но в логе всё равно остаются те же ошибки. Видимо, ещё нужно менять charset сервера / БД / клиента?

**Comment by blackav** [comment]
Создал #132

**Comment by blackav** [comment]
> > Если utf8 в mariadb не умеет в 4-байтный UTF-8, то это надо во всех таблицах менять.
> 
> Да, наверное, лучше поменять во всех таблицах.
> 
> Но похоже, что этого недостаточно. Попробовал поменять charset конкретно у таблиц для телеграма ([vvd170501@5fa4fe9](https://github.com/vvd170501/ejudge/commit/5fa4fe90a600e9f0065ad282d045487115fa36ce)), пересоздал соответствующие таблицы, но в логе всё равно остаются те же ошибки. Видимо, ещё нужно менять charset сервера / БД / клиента?

Там еще кодировка connection и наверное еще где-то.

**Comment by blackav** [comment]
попробуйте с коммитом fa06a7ee0ece12bbd837ef3b629737413fbac827

**Comment by vvd170501** [comment]
Собрал с https://github.com/vvd170501/ejudge/commit/4c9001c822a8e322ab857580f17c12158753aa50 (коммиты 99679f8..50de3ec, применённые к 3.10.0).
Добавление пользователей в БД работает, других ошибок пока нет.
