### ISSUE TITLE
Настройка порогов для отправки напоминаний в Telegram-чат через конфиг контеста

### ISSUE THREAD

**Issue by vvd170501** [blackav/ejudge#133]
https://ejudge.ru/wiki/index.php/Telegram_bot:_настройка_административных_уведомлений

> Раз в сутки рассылаются напоминания о посылках в статусе Pending Review.

Сейчас (в версии 3.10.0) напоминания отправляются при выполнении одного из следующих условий:
- [В контесте 20+ посылок со статусом PR](https://github.com/blackav/ejudge/blob/d0ea326be6b085034054dc6c30afb4bfe0f19325/plugins/telegram/telegram.c#L1127) (также константа 20 используется [здесь](https://github.com/blackav/ejudge/blob/d0ea326be6b085034054dc6c30afb4bfe0f19325/lib/serve_2.c#L978))
- [Хотя бы одна посылка старше 48 часов имеет статус PR](https://github.com/blackav/ejudge/blob/d0ea326be6b085034054dc6c30afb4bfe0f19325/lib/master_html.c#L738)
- [Есть хотя бы один неотвеченный клар старше 48 часов](https://github.com/blackav/ejudge/blob/d0ea326be6b085034054dc6c30afb4bfe0f19325/lib/master_html.c#L742)

Хочется уметь настраивать пороги для напоминаний через конфиг контеста.
1. Минимальное количество посылок со статусом PR.
2. Время, через которое посылка со статусом PR становится "слишком старой".
3. Время для неотвеченных кларов. Оно может отличаться от времени для посылок.

**Comment by blackav** [comment]
попробуйте добавить дополнительные параметры в конфигурационный файл serve.cfg

**Comment by vvd170501** [comment]
А какая логика у разделения параметров между contest.xml и serve.cfg?
Сейчас в contest.xml есть `telegram_admin_chat_id` и `telegram_bot_id`.
В serve.cfg есть (вроде) только `notify_on_submit` для отдельных задач.

Если добавлять параметры напоминаний, то они должны быть глобальными для контеста. Чем в этом случае serve.cfg лучше contest.xml?

**Comment by vvd170501** [comment]
Для моего юзкейса нужно слишком много настраиваемых параметров (пороги и частота напоминаний, возможно, отдельный чат, чтобы не смешивать напоминания с уведомлениями о CF, пинг пользователей в групповых чатах).
Решил сделать отдельного внешнего бота.
