### ISSUE TITLE
Telegram-плагин: поддержка 64-битных id пользователей и чатов

### ISSUE THREAD

**Issue by vvd170501** [blackav/ejudge#134]
Если id пользователя не представим знаковым 32-битным целым числом, то при добавлении пользователя в БД происходит ошибка:
```
2023-01-06T21:37:55Z:error:database error: Out of range value for column 'id' at row 1
```

Также 64-битные id могут использоваться для чатов (см. https://core.telegram.org/bots/api).

Откуда берётся ошибка: в mariadb `INT(18)` влияет только на ширину выводимого значения, INT всё равно остаётся 32-битным. Поэтому нужно использовать BIGINT.

Пример исправления (без миграции старых версий БД): https://github.com/vvd170501/ejudge/commit/42f3252087d3a9aa8609854a2209d6307b4f9a22
`update_id`, согласно документации Telegram API, представим знаковым 32-битным целочисленным типом, поэтому для него я оставил INT.

**Comment by blackav** [comment]
d55cd753869e043e99a0948e5275c078446761c1
