### ISSUE TITLE
Задачи с зависимостями в accepting mode контеста с типом olympiad

### ISSUE THREAD

**Issue by arseny2606** [blackav/ejudge#135]
Если контест с типом olympiad находится в accepting mode, то, если есть посылки с любым вердиктом ко всем зависимостям задачи, то она начинает отображаться в списке. Однако, если хотя бы одна задача из зависимостей не имеет статуса OK, то послать в зависимую ничего нельзя.
В таком случае нужно либо не отображать зависимую задачу (что не очень логично), либо сделать возможность отправлять посылки задачам с зависимостями в accepting mode контеста с типом olympiad при любых вердиктах у зависимых задач (конечно, если по ним есть хотя бы одна посылка).

**Comment by blackav** [comment]
Проверил на пробном контесте. Задача начинает отображаться, когда задачи, от которой она зависит, получает статус Accepted или Ok. Кажется, это ожидаемое поведение. Уточните, пожалуйста, кейс, когда проявляется ошибка.

**Comment by arseny2606** [comment]
Output-only задача 1_file зависит от решения short-answer задачи 1. Изначально она не отображается в списке задач:
<img width="273" alt="Снимок экрана 2023-01-19 в 13 54 48" src="https://user-images.githubusercontent.com/37185492/213424612-0e557fa0-5c62-43e7-9e5a-510fcffddafa.png">
После решения задачи 1, которое получило вердикт "Неправильный ответ" (а участник видит только "Принято на проверку"), эта задача появляется в списке задач:
<img width="609" alt="Снимок экрана 2023-01-19 в 13 54 57" src="https://user-images.githubusercontent.com/37185492/213424836-f1b1fc85-385f-4752-a2ca-7777b9d52824.png">
<img width="687" alt="Снимок экрана 2023-01-19 в 13 55 08" src="https://user-images.githubusercontent.com/37185492/213424884-566a5289-0943-4206-8e38-0cb359848aec.png">
<img width="276" alt="Снимок экрана 2023-01-19 в 13 55 02" src="https://user-images.githubusercontent.com/37185492/213424917-a99d9b58-f6b8-4c4f-a89d-27538096798e.png">
Но при этом посылку в зависимую задачу отправить нельзя, поскольку "Решены не все требуемые задачи":
<img width="578" alt="Снимок экрана 2023-01-19 в 13 56 42" src="https://user-images.githubusercontent.com/37185492/213425019-ecb39d9d-2195-47e4-b329-e55a4e94b10a.png">
