### ISSUE TITLE
Дорешивание в виртуальных турнирах

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#138]
В виртуальных турнирах дорешивание работает своеобразно.

1. Если запустить дорешивание, то дорешивать могут только те, кто не нажал на кнопку "Закончить виртуальный турнир".
2. Если у участника закончилось время и он не нажал на кнопку "Закончить виртуальный турнир", то он сможет дорешивать.
3. Если участник начал виртуальный турнир после включения режима дорешивания, то он ничего не сможет делать - ни сдавать, ни дорешивать.

Предлагаемое поведение - после включения режима дорешивания дорешивать могут все, независимо от того, нажимали ли они кнопку или нет.

Сложнее вопрос, что делать с теми, кто хочет начать турнир уже после того, как включён режим дорешивания. Или что делать с теми, у кого виртуальный турнир не закончился на момент начала дорешивания. Наверное, самое простое - это дать им возможность уже бесконечно сдавать решения, но не отображать новые посылки в таблице.

**Comment by blackav** [comment]
то есть предлагается режим дорешивания сделать по сути как принудительное завершение виртуального турнира для всех участников, после чего любые участники могут посылать решения, но они в таблицу не попадут. тогда режим дорешивания нельзя отменить?

**Comment by blackav** [comment]
Сделал так: после включения режима дорешивания участники не могут стартовать виртуальный турнир, но все задачи доступны для сдачи в режиме дорешивая. Те, у кого в момент включения дорешивания виртуальный турнир еще не закончился, заканчивают виртуальный турнир в "зачетном" режиме, после чего могут сдавать в режиме дорешивания.
