### ISSUE TITLE
Импорт из полигона не работает, если включён параметр "Only my activity"

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#139]
У пользователя в полигоне на странице Problems включён чекбокс "Only my activity", из-за этого не все задачи отображаются в списке задач.

Если этот пользователь пытается сделать импорт контеста или задачи из Полигона, но при этом на странице Problems эта задача не отображается, хотя права на эту задачу у пользователя есть, то импорт будет неудачным с сообщением, что задача NOT_FOUND.

Если зайти в полигон  под этим пользователем и снять чекбокс "Only my activity", то импортировать задачи получится.

Вероятно, с чекбоксом "Only favorite" будет то же самое.

Импорт из полигона должен снимать эти чекбоксы при загрузке списка задач.

**Comment by blackav** [comment]
Как-то это не очень выглядит, чтобы еще галочки устанавливать/снимать. Видимо лучше оставить как есть, пока у полигона не появится адекватный API.

**Comment by andgein** [comment]
А вот это апи не подходит?

https://docs.google.com/document/d/1mb6CDWpbLQsi7F5UjAdwXdbCpyvSgWSXTJVHl52zZUQ/edit

**Comment by blackav** [comment]
Там только скачивание, причем с другой аутентификацией, чем основной API. Собрать пакет для linux нельзя было никак. В общем, что-то у меня не сошлось в итоге.

**Comment by mezun7** [comment]
> Там только скачивание, причем с другой аутентификацией, чем основной API. Собрать пакет для linux нельзя было никак. В общем, что-то у меня не сошлось в итоге.

Для pcms написали импортер через api как раз.
https://github.com/ilsaf13/PolygonContestImporter

**Comment by blackav** [comment]
Поддержка polygon API уже была в коде, нужно чуть доработать

**Comment by blackav** [comment]
Polygon API теперь поддерживается.
