### ISSUE TITLE
На странице "Standings" ошибочно применяется штраф за посылки со статусом "OK"

### ISSUE THREAD

**Issue by vvd170501** [blackav/ejudge#145]
### Описание проблемы

Если в контесте используетсяя система KIROV, без опций `ignore_unmarked` и `score_latest_or_unmarked`, то на странице "Standings" предыдущие  посылки со статусом "OK" ошибочно учитываются при вычислении штрафа. В частности, из-за этого некорректно считается балл для посылок с положительным `score_adj`, если у пользователя были предыдущие правильные посылки в этой задаче.

Пример списка посылок:
![image](https://user-images.githubusercontent.com/36827317/219951544-d4842e8f-b2f3-4be6-aa9b-33d0224dfe78.png)

Так отображается балл в "Standings" в интерфейсе администратора:
![Screenshot from 2023-02-19 16-29-03](https://user-images.githubusercontent.com/36827317/219951682-aca6d508-a83f-4e8c-9621-d7a65ee7c68e.png)

(в таблице 108 баллов, хотя должно быть 110)

В интерфейсе пользователя также отображается некорректный балл, т.к. для обеих таблиц используется один и тот же код.

### Причина

Проблема заключается в том, что для вычисления штрафа используется `att_num` - суммарное число посылок пользователя в конкретной задаче, а не количество частичных решений.

### Возможный вариант исправления

vvd170501/ejudge@36bfcf8d8 + vvd170501/ejudge@40cf178e8. Исправлен подсчёт только для контестов без опций `score_latest_or_unmarked` и `ignore_unmarked`.
- Посылки со статусами OK, PR, SM не учитываются в штрафе.
- В формулу штрафа включаются все посылки со статусом PT, а не только те, которые были до первого OK'а (так же, как в таблице посылок на главной странице).
- Посылки со статусом DQ не учитываются в `sol_att` - в таблице посылок они дают только отделный штраф `disqualified_penalty`, но не увеличивают штраф от `run_penalty`.

Возможно, этот коммит ломает подсчёт баллов для контестов с `ignore_unmarked` (должны ли непомеченные посылки со статусом OK учитываться в штрафе?).

Отображение баллов в Standings в контестах с `score_latest_or_unmarked` не проверял, но, скорее всего, для них эта проблема тоже актуальна.

**Comment by blackav** [comment]
кажется, наоборот, нужно все предыдущие попытки, кроме rejected и ignored штрафовать

**Comment by vvd170501** [comment]
Почему? Если пользователь сдал решение, получил ОК, а потом решил переотправить его (например, с добавленным комментарием), то как-то странно за это штрафовать.
