### ISSUE TITLE
Неправильно выводится информация в external.xml

### ISSUE THREAD

**Issue by vv73** [blackav/ejudge#150]
При выводе результатов в external.xml не учитываются штрафы за количество посылок.

Например, 
```
 <run run_id="6" time="1359" run_uuid="c0ead88b-7b72-4062-91a3-c2db1b20ea3a" status="PT" user_id="19958" prob_id="30" mime_type="text/plain" score="6" test="0" nsec="320043000" passed_mode="yes"/>
    <run run_id="7" time="1378" run_uuid="0a057d05-772a-41fb-8893-3c706290eecf" status="OK" user_id="19958" prob_id="30" mime_type="text/plain" score="10" test="1" nsec="894498000" passed_mode="yes"/>
```
Штраф в 1 балл за вторую сдачу, который виден в интерфейсе участника, не отображается в xml.

Эффект наблюдался в контесте типа KIROV, Ejudge 3.9

**Comment by blackav** [comment]
Так и должно быть. В external.xml выводится только балл, полученный при тестировании. Штрафы и другие поправки к баллам должны уже вычисляться при обработке XML.

**Comment by vv73** [comment]
Штрафы по задачам могут быть разные. Как это учитывать?
