### ISSUE TITLE
Deleting contest

### ISSUE THREAD

**Issue by alexbagirov** [blackav/ejudge#2]
Hello!
How can I delete a contest?

Please, make such function so users can make it automatically.

**Comment by aropan** [comment]
I do so:
```bash
ejudge-control stop
cd ~/judges/
rm $CID -r
rm data/contests/$CID.xml
ejudge-control start
```

But more often hide contests, I delete rarely.

**Comment by blackav** [comment]
"delete contest" function is too dangerous
