### ISSUE TITLE
не могу запустить ejudge-install.sh

### ISSUE THREAD

**Issue by Bahodir94** [blackav/ejudge#23]
Подскажите почему не получается sudo /home/ejudge/ejudge/ejudge-install.sh
![xa](https://cloud.githubusercontent.com/assets/17880294/26283418/8712a152-3e41-11e7-99c9-bd5b1e6e84db.png)
что мне делать?

**Comment by blackav** [comment]
Запустите ejudge-setup

**Comment by Bahodir94** [comment]
Вот смотрите, я все сделал как в инструкции.
![z](https://cloud.githubusercontent.com/assets/17880294/26288994/ad2618d8-3eb4-11e7-9c25-421dab151b3c.gif)

**Comment by Bahodir94** [comment]
вы можете сделать демонстрации видео установка от 0 до создать турнира. Пожалуйста!
Я не могу уже 5 день не получается. Установил Mooshak, Sharif-judge но оба не получилось.
Помогите пожалуйста очень нужна.

**Comment by blackav** [comment]
Файл сохраняется в текущий каталог, то есть тот, из которого запускалась программа ejudge-setup. Поэтому ejudge-install.sh надо запускать из него, то есть ./ejudge-intall.sh.

**Comment by Bahodir94** [comment]
Пожалуйста покажите с нулям. Если не трудно.

**Comment by blackav** [comment]
Пожалуйста, задавайте конкретные вопросы.
