### ISSUE TITLE
Export archives in the background

### ISSUE THREAD

**Issue by blackav** [blackav/ejudge#245]
Текущая реализация выполняет формирование архива посылок непосредственно в обработчике HTTP-запроса. Это плохо, так как блокируются другие запросы, и, поскольку создание архива - длительный процесс, сервер рано или поздно закрывает страницу по тайм-ауту.

Необходимо выполнять создание архива как фоновую задачу.

**Comment by dkirienko** [comment]
О да, всегда когда хочешь скачать 10.000 сабмитов, приходится делить их на части...

А ещё когда делаешь rejudge displayed runs, выбрав те же 10.000 сабмитов, тоже страница отваливается по таймауту.

**Comment by blackav** [comment]
с rejudge runs все проще: несмотря на тайм-аут операция все-таки выполняется

**Comment by blackav** [comment]
А вообще, при большом количестве сабмитов должен предлагаться background режим. Неужели он сломался?
