### ISSUE TITLE
Feature request: опция, чтобы запускать не все тесты по системе KIROV

### ISSUE THREAD

**Issue by ov7a** [blackav/ejudge#26]
Сейчас KIROV прогоняет все тесты (в то время как ACM - до первого ошибочного).
Хотелось бы имень возможность настроить ejudge так, чтобы он оценивал по системе KIROV, но при этом запускал тесты только до первого ошибочного.

**Comment by ov7a** [comment]
В приниципе, этого можно достичь с помощью системы Moscow, но по ней отсутствует документация и мне пришлось лезть в код, чтобы понять, какие данные ей нужны.

Кроме того, в установленной у меня версии (ejudge 3.5.1+ (GIT 57c08df)) нельзя было задать full_score для задачи через веб-интерфейс (возможно, это уже исправлено).

**Comment by apathism** [comment]
Технически такая возможность есть в KIROV с помощью интерактивной оценивающей программы. Она может давать пропущенным тестам статус Skipped.

См. https://ejudge.ru/wiki/index.php/%D0%9E%D1%86%D0%B5%D0%BD%D0%B8%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B#.D0.98.D0.BD.D1.82.D0.B5.D1.80.D0.B0.D0.BA.D1.82.D0.B8.D0.B2.D0.BD.D1.8B.D0.B5_.D0.BE.D1.86.D0.B5.D0.BD.D0.B8.D0.B2.D0.B0.D1.8E.D1.89.D0.B8.D0.B5_.D0.BF.D1.80.D0.BE.D0.B3.D1.80.D0.B0.D0.BC.D0.BC.D1.8B

**Comment by blackav** [comment]
Да, это реализуется через интерактивные оценивающие программы, например, gvaluer.
Пример конфигурационных файлов есть здесь: https://github.com/blackav/zaoch-final-2015
