### ISSUE TITLE
Не совпадают форматы CSV для дампа и загрузки посылок в CSV

### ISSUE THREAD

**Issue by ov7a** [blackav/ejudge#28]
Во-первых, в дампе полей больше. Во-вторых, они называются по-другому (это вообще за гранью добра и зла). 
Документация отсутствует.

**Comment by blackav** [comment]
Названия полей изменены. Но никогда не предполагалось, что выгруженный CSV можно будет загружать обратно и все данные сохранятся.

**Comment by ov7a** [comment]
Было бы неплохо добавить тогда инструкцию, как переносить посылки из одного контеста в другой (или между разными инстансами ejudge). Так-то с помощью этих дампов можно переносить метаинформацию, а сами файлы - вручную.

**Comment by blackav** [comment]
из одной инсталляции в другую - mysqldump. Между контестами - штатного способа нет, учитывая, что нужно для каждой посылки генерировать новый uuid.
