### ISSUE TITLE
size of mime_type field in runs table (64) is too small

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#286]
Размер поля mime_type в таблице runs объявлен, как varchar(64), между тем длина строки "application/vnd.openxmlformats-officedocument.presentationml.presentation" составляет 73 символа.

**Comment by blackav** [comment]
fixed in #e9f016cbc8790e133a9e5dd1fa4b360c67b31050

**Comment by blackav** [comment]
fixed
