### ISSUE TITLE
XSS в форме авторизации

### ISSUE THREAD

**Issue by abel1502** [blackav/ejudge#29]
В поле "Выйти из системы [логин]" подставляется введенный пользователем логин без обработки html. Таким образом, вход под логином вида "qqq<script>alert(document.cookie);</script>" показывает куки пользователя и т.д.

**Comment by blackav** [comment]
Пользователь не может создавать такие логины.

**Comment by abel1502** [comment]
Этого не требуется: такая кнопка появляется даже если логина не существует

**Comment by blackav** [comment]
Но это не влияет на других пользователей, не сохраняется в базу и т. п.

**Comment by abel1502** [comment]
Это да, но я сейчас не говорю про векторы эксплуатации. Я говорю, что есть уязвимость, подвергающая пользователя опасности. Я говорю, что ее нужно исправить. Это все)

**Comment by blackav** [comment]
Fixed in 3.7.0
