### ISSUE TITLE
Support priorities for compilation queue

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#292]
Как я понимаю, сейчас очередь компиляции не учитывает приоритеты тестирования задач.

В результате возникает ситуация, что при большом перетестировании (ручном), производимом одновременно с возможной сдачей решений участниками, решение участника хотя и тестируется с более высоким приоритетом, может слишком долго проходить очередь компиляции.

Предлагается для очереди компиляции использовать такие же приоритеты, как и для очереди тестирования задач.

**Comment by blackav** [comment]
Проверил, по факту все так и происходит: при компиляции действуют те же приоритеты, что и при тестировании потом.
