### ISSUE TITLE
Subtasks on Ejudge

### ISSUE THREAD

**Issue by TheStranger512** [blackav/ejudge#3]
Hi, I have installed Ejudge in Fedora Linux and everything works fine, but as I see on most other judges there are subtasks and solving problems, which have subtasks is more interesting, is there any way to create subtasks on Ejudge? Thanks in advance!

**Comment by blackav** [comment]
Sorry, I don't understand what "subtask" means. Could you, please, elaborate?

**Comment by alexbagirov** [comment]
@blackav, подзадачи.

**Comment by blackav** [comment]
спасибо, я понимаю что это "подзадачи". Но что конкретно вы имеете в виду? Можете пример привести?

**Comment by alexbagirov** [comment]
Я не знаю. Не я же вопрос задал :)

**Comment by TheStranger512** [comment]
like in this problem: http://wcipeg.com/problem/ioi1511
there are subtasks in the end of statement, if you solve this problem with smaller limitations judge will give you  some precise score in this problem. for example if you solve first subtask of this problem it will give you 10points (while solving original limitations would give you 100 points). The good thing about subtasks is that if your problem is right for 10 tests out of 12 in one subtask, you achieve 0 points in this problem.

**Comment by blackav** [comment]
Yes, it is supported.
Here's a sample specification of such grouping: https://github.com/blackav/zaoch-final-2015/blob/master/day1/problems/elections/valuer.cfg

**Comment by TheStranger512** [comment]
Its great, thanks for fast response and thanks for judging system :smile:
