### ISSUE TITLE
Select-All checkbox does not work on Registered Users page

### ISSUE THREAD

**Issue by vv73** [blackav/ejudge#301]
Вроде, плохо работает галочка "Выделить все".
Выделяется все, но потом операция применяется только к верхней ячейке.
Если выделять все руками, ставить каждую галочку, применяется как ожидается.
![image](https://github.com/blackav/ejudge/assets/7459795/75a802fe-c775-43d2-bb3e-2a1099134391)

**Comment by blackav** [comment]
Проверил, все работает корректно

**Comment by dkirienko** [comment]
А вот у меня воспроизводится.

**Comment by dkirienko** [comment]
На olympiads.ru в контесте 420 под пользователем dk воспроизводится.

**Comment by blackav** [comment]
Какую операцию ты применял?

**Comment by blackav** [comment]
Можешь попробовать повторить эксперимент?

**Comment by blackav** [comment]
See #329

**Comment by blackav** [comment]
#329 completed

**Comment by dkirienko** [comment]
Разобрались, виновато расширение для Chrome https://chromewebstore.google.com/detail/ndlkkeakaopmfijknecpgfoaebiimbog?hl=ru&utm_source=ext_sidebar
