### ISSUE TITLE
Privileged user can't be registered to contest via serve-control user editor

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#304]
User editor из serve-control не позволяет регистрировать на контесты привилегированных пользователей.

Как воспроизвести. Воспроизводится, например, на olympiads.ru
1. Откроем User editor из serve-control
2. Найдём пользователя c uid 5117.
3. Выберем его и попробуем через registration operation зарегистрировать на контест 401.
4. Ничего не получилось, пользователь не добавился в контест.
5. Чекбокс "Perform the operation even for PRIVILEGED users" не помогает.
6. Обычный пользователь через этот интерфейс регистрируется, например, я смог так зарегистрировать пользователя с uid 238.

**Comment by blackav** [comment]
Можешь попробовать повторить эксперимент?

**Comment by blackav** [comment]
See #329

**Comment by blackav** [comment]
#329 completed
