### ISSUE TITLE
Как избавиться от "NOTE: The file checksum has been changed!"?

### ISSUE THREAD

**Issue by ov7a** [blackav/ejudge#31]
Сабж. Возникает сообщение при просмотре протокола проверки посылки в ответе ("А").
Есть какой-нибудь способ пересчитать эти хэши? И вообще, при каких условиях показывается это сообщение? Тесты при этом грузятся актуальные.

Пробовал check contest settings - не помогло.

**Comment by blackav** [comment]
Это сообщение выдается, когда включен режим полного сохранения файлов в протоколе (enable_full_archive) и когда файл с тестом был изменен после тестирования решения. Чтобы сообщение исчезло, нужно перетестировать решение.

**Comment by ov7a** [comment]
Пробовал из-под администратора rejudge и full rejudge - не помогло. 
А если отключить enable_full_archive, то тогда правильные ответы всегда будут грузиться из tests и такая ошибка не возникнет?

**Comment by blackav** [comment]
Fixed in 3.7.0
