### ISSUE TITLE
Как обновить данные из mуsql?

### ISSUE THREAD

**Issue by ov7a** [blackav/ejudge#32]
Подключился к mysql напрямую, изменил данные. Если читаю из mysql - обновленные данные вижу, из веб-интерфейса и ejudge-edit-users - не вижу этих изменений. В ejudge есть какой кэш промежуточный? Как заставить его перечитать данные из базы?

**Comment by blackav** [comment]
killall -HUP ej-users

**Comment by ov7a** [comment]
Команда помогла, спасибо!
