### ISSUE TITLE
Статус SE для питона

### ISSUE THREAD

**Issue by ov7a** [blackav/ejudge#33]
При возникновении исключения в программе, написанной на питоне, или при ошибке синтаксиса (когда тоже выкидывается исключение интерпретатором) результатом проверки будет SE, хотя по идее там должен быть либо RT, либо CE соответственно.

Эта проблема возникает из-за того, что при выводе стека вызовов происходит чтение системных файлов, что запрещено модулем безопасности.

**Comment by apathism** [comment]
По всей видимости, зависит от конфигурации питона при сборке. На ArchLinux с 4.9 получается RT, но на Fedora я видел, что получается SE.

**Comment by ov7a** [comment]
Да, у меня проблема на виртуалке с федорой.
Еще заметил, что проблема может быть еще и с `abrt`:
```
Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
```

**Comment by blackav** [comment]
Можно отключить в турнире опцию 'detect_violations'.

Какая у вас версия ядра Linux?

**Comment by ov7a** [comment]
Версия `4.1.19-cher1`. 
Но если выключить `detect_violations`, тогда ведь реальные случаии SE не будут обнаруживаться?

**Comment by blackav** [comment]
Будет просто runtime error. Все равно все опасные вызовы будут заблокированы.
