### ISSUE TITLE
Add MathJAX support to the statements

### ISSUE THREAD

**Issue by blackav** [blackav/ejudge#332]
Добавить в заголовки страниц подгрузку скриптов MathJAX

**Comment by dkirienko** [comment]
Прикольно, я сам пропатчил ejudge в школе, чтобы он подгружал MathJax.

**Comment by dkirienko** [comment]
Только вот я столкнулся с таким кейсом. Я проводил контрольную и заблочил весь интернет. И после этого страницы ejudge загружались безумно долго. После этого я перенёс MathJax на свой сервер.

**Comment by blackav** [comment]
Патч для mathjax существует уже давно, надо все необходимые файлы подтащить.
