### ISSUE TITLE
Первая команда, сдавшая задачу, на Virtual ACM

### ISSUE THREAD

**Issue by apathism** [blackav/ejudge#34]
В ejudge 3.7 появилась новая функция, которая подсвечивает команду, получившую первый OK по каждой задаче. Однако подсветка работает некорректно в режиме Virtual ACM, так как выбирается первая сдача по астрономическому времени, а не по времени в турнире.

Например, на картинке по задаче B первый OK был получен в 0:15 в турнире, но он был сделан командной, которая писала турнир позже по астрономическому времени.

![screenshot_20171001_120229](https://user-images.githubusercontent.com/364939/31053234-9aae5396-a6a1-11e7-94b0-44849790839c.png)

**Comment by apathism** [comment]
А ещё, как выяснилось, в Virtual ACM не работает заморозка монитора.

**Comment by blackav** [comment]
Что значит "не работает"?

**Comment by blackav** [comment]
Баг с первым решившим закрываю, баг с заморозкой - отдельно.

**Comment by blackav** [comment]
Fixed in v3.7.1
