### ISSUE TITLE
clang + sanitizer

### ISSUE THREAD

**Issue by ov7a** [blackav/ejudge#36]
Пытаюсь подобрать альтернативу g++-vg, т.к. он очень медленный.

Самый перспективный вариант - clang с sanitizer'ами. 
https://github.com/google/sanitizers
https://clang.llvm.org/docs/AddressSanitizer.html
Пока удалось только заставить работать address sanitizer.
Для этого в флагах компиляции поставил `-fsanitize=address -g -fno-omit-frame-pointer`
И добавил start_env для linux_shared: `start_env = "ASAN_OPTIONS=symbolize=0:detect_leaks=0"`
(кстати, это окружение можно где-нибудь через пользовательский интерфейс установить?)

Какие-то ошибки работы с памятью удается обнаружить, но есть проблемы:
1. `LeakSanitizer does not work under ptrace (strace, gdb, etc)` - из-за этого пришлось поставить `detect_leaks=0`.
2. При попытке вывести стек с именем файла/номером строки - security violation, из-за того что вызывается llvm-symbolizer. Поэтому  `symbolize=0`
3. undefined sanitizer вообще не работает, т.к. ему не дают доступ к памяти.

В связи с этим вопрос - есть ли какой-нибудь опыт по внедрению санитайзеров? Или, возможно, какие-нибудь идеи, как решить возникшие проблемы?

**Comment by blackav** [comment]
В gcc есть -fsanitize, с ним, вроде бы, таких проблем нет

**Comment by ov7a** [comment]
Попробовал `gcc` с флагами компиляции `-std=c++11 -fsanitize=address -g -fno-omit-frame-pointer  -static-libasan`
Получаю:
```
==29614==WARNING: reading executable name failed with errno 1, some stack frames may not be symbolized
==29614==WARNING: reading executable name failed with errno 1, some stack frames may not be symbolized
==29614==Sanitizer CHECK failed: ../../../../libsanitizer/sanitizer_common/sanitizer_procmaps_linux.cc:20 ((ReadFileToBuffer("/proc/self/maps", &proc_maps->data, &proc_maps->mmaped_size, &proc_maps->len))) != (0) (0, 0)
```

**Comment by blackav** [comment]
для -fsanitize=address нужно отключать безопасный режим (disable_security) и устанавливать большой лимит на адресное пространство (max_vm_size=512M)

**Comment by ov7a** [comment]
Без безопасного режима и `clang` работает нормально. 
У задачи стоит `max_vm_size = 4294967295`
