### ISSUE TITLE
A bug in dyntrie implementation causes ej-contests to crash frequently

### ISSUE THREAD

**Issue by batuzovk** [blackav/ejudge#365]
In ej-contests.log it looks like this:

```
Fatal signal 6 received:
0x55e006c3b270 fatal_signal_handler
        unix/startstop.c:52
0x7f36fb7fd13f ???
        ./nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f36fb65fce1 __GI_raise
        ../sysdeps/unix/sysv/linux/raise.c:51
0x7f36fb649536 __GI_abort
        ./stdlib/abort.c:79
0x55e006bfe8e3 dyntrie_get
        lib/dyntrie.c:294
0x55e006baa12c test_count_cache_get
        lib/test_count_cache.c:158
0x55e006b8b4dc serve_run_request
        lib/serve_2.c:2675
0x55e006b8eee3 serve_read_compile_packet
        lib/serve_2.c:3852
0x55e006abeb6f ns_loop_callback
        lib/new_server_html.c:698
0x55e006b80c21 nsf_main_loop
        lib/server_framework.c:1578
0x55e006aa017e main
        bin/ej-contests.c:1071
0x7f36fb64ad09 __libc_start_main
        ../csu/libc-start.c:308
0x55e006a9d0e9 ???
        ???:0
0xffffffffffffffff ???
        ???:0
```

A minimal example with which I was able to reproduce the issue:

```
#include <stdio.h>
#include <stdlib.h>
#include "dyntrie.h"

int main(void)
{
    struct dyntrie_node *root = NULL;
    void *old_value = NULL;
    printf("insert = %d\n", dyntrie_insert(&root, "abc", 42, 0, &old_value));
    printf("get = %d\n", (int)(uintptr_t)dyntrie_get(&root, "abcdef"));
    return 0;
} 
```

The key here is to search for a longer string that contains one of the existing strings as a prefix. `dyntrie_lookup` checks `item->key_length` characters and then returns 1 if they match. `dyntrie_get` aborts if the returned node is a leaf, but not all characters in the searched string were matched.

I would say `dyntrie_get` should just return NULL instead of aborting, but I'm not entirely sure.

**Comment by blackav** [comment]
Please, show the configuration settings, that cause crashes

**Comment by batuzovk** [comment]
I'm not sure which configuration setting causes crashes. Over years we've accumulated over 700 contests and several thousands users. Everything used to work with ejudge 3.7.9, but after updating to 3.10.3 we've started getting crashes. This one was the most worrying because we have no idea what exactly causes it, yet it happens almost once every day.

That said, I believe my minimized example proves that there is an issue with dyntrie implementation. While it is not documented, I doubt that aborting on a well-formed search query was the intended behavior. I've found this example by looking at the code and trying to guess what can cause the crash. Replacing corresponding `abort()` with `return NULL` seem to have fixed this crash (but there are others).

**Comment by blackav** [comment]
The current version works on multiple sites with several thousand users right now and without any problems. If that abort issue was common, crashes would be regular on all the sites running ejudge. It could be well possible, that the discussed abort is a manifestation of some other problem. So, it would be very helpful to track it down to the configuration setting that triggers such behavior.

**Comment by batuzovk** [comment]
I get what you are saying, but unfortunately it is really hard to track the issue to a specific setting. I mean, something broke among those 700 contests. I don't even know which one is causing the trouble.

We have somewhat old directory layout with tests stored in `/home/judges/<contest_id>/tests/<problem_short_name>`. We also have short names that are prefixes of other short names (e.g. `01-1` and `01-10`). This is probably a rather uncommon combination that might not be present on other sites.

In our case directories `/home/judges/002001/tests/01-1` and `/home/judges/002001/tests/01-10` are both valid test locations for different problems withing the same contest. Without trailing `/` the first one is a prefix of the second one, and thus they trigger the issue shown by minimized example. If other sites use different directory layout they might never trigger the bug.

But these are my guesses, I haven't debugged ejudge in such details.

**Comment by blackav** [comment]
Thanks
