### ISSUE TITLE
Заморозка таблица при дорешивании

### ISSUE THREAD

**Issue by andrei-ilyin** [blackav/ejudge#37]
Заморозка таблицы участников при дорешивании для контестов по системе OLYMPIAD больше не работает. Теперь все участники (а не только судьи) видят в итоговой таблице результаты с учётом посылок в дорешку, даже несмотря на то что в заголовке стоит "заморожено"

**Comment by blackav** [comment]
Как это должно работать? Шлите merge request, если вы можете это исправить.
