### ISSUE TITLE
start_cmd игнорируется в языках, где используется valgrind.

### ISSUE THREAD

**Issue by makkarpov** [blackav/ejudge#4]
Здравствуйте.

Столкнулся с такой проблемой - в одна и та же задача, два разрешенных языка - gcc и gcc-vg. При проверке решения на языке gcc отрабатывает скрипт в start_cmd, при проверке на gcc-vg - вместо него отрабатывает valgrind, и скрипт вообще не запускается.

**Comment by blackav** [comment]
Да, valgrind переопределяет start_cmd.

**Comment by makkarpov** [comment]
Можно ли это исправить, чтобы, например, ./start_cmd конкатенировался - `runvg ./s_cmd ./solution`. Если можно - то выбирать порядок конкатенации - `valgrind ./s_cmd` или `./s_cmd valgrind`.

**Comment by blackav** [comment]
Вы какую задачу хотите решить с помощью start_cmd?

**Comment by makkarpov** [comment]
Запустить проверяющую программу для того, чтобы посредством FIFO с ней взаимодействовать (интерактор тут неприменим, т.к. FIFO должен быть именованный).

**Comment by blackav** [comment]
Для этого лучше использовать init_cmd

**Comment by blackav** [comment]
А еще какой смысл разрешать одновременно и valgrind, и обычный режим исполнения?

**Comment by makkarpov** [comment]
Изначально был разрешен только valgrind, а после того, как не сработал - пришлось разрешать только обычный. По поводу init_cmd - попробую, спасибо.

**Comment by makkarpov** [comment]
Как я понял, при использовании init_cmd нет возможности получить PID, что бы взаимодействовать с ним, например, сигналами?

**Comment by statgrad** [comment]
Даже интересно, почему вся эта переписка приходит мне? 

Дмитрий А. Путимцев
МЦНМО ЦПМ

**Comment by makkarpov** [comment]
![image](https://cloud.githubusercontent.com/assets/1329592/11045447/8d6cccc4-8738-11e5-856d-f5598ec6e529.png)

**Comment by blackav** [comment]
PID недоступен, так как процесс еще не запущен.
Для взаимодействия с помощью сигналов лучше интерактор.

**Comment by makkarpov** [comment]
Ну вот start_cmd - обобщение интерактора на произвольную структуру взаимодействия, где сами интеракторы неприменимы.  Можно ли как-нибудь реализовать конкатенацию языкового start_cmd и задачного?

**Comment by statgrad** [comment]
Повторно интересуюсь: зачем получаю эти сообщения?

--------------------------------------------
МЦНМО  ЦПМ
Дмитрий А. Путимцев
 

-----Original Message-----

**Comment by makkarpov** [comment]
Потому что вы на них подписаны.

**Comment by statgrad** [comment]
Не могу вспомнить, когда я подписывался. 
Как отписатья?

--------------------------------------------
МЦНМО  ЦПМ
Дмитрий А. Путимцев
 

-----Original Message-----

**Comment by makkarpov** [comment]
Глобально - Unwatch на главной странице проекта. Локально - Unsubscribe.

![image](https://cloud.githubusercontent.com/assets/1329592/11092788/f66662e4-8896-11e5-84d4-eb9a1b4042b3.png)
![image](https://cloud.githubusercontent.com/assets/1329592/11092795/02f202de-8897-11e5-8955-cfc5e2c570ee.png)

**Comment by blackav** [comment]
Добавил в master:
https://github.com/blackav/ejudge/commit/268c0b6a51eeb7282cbee205300907c8664402a2

**Comment by makkarpov** [comment]
Спасибо. Как я понял, порядок сейчас - `start_cmd языка` `start_cmd задачи`?

**Comment by blackav** [comment]
наоборот, например:
your_start_cmd valgrind prog_to_test

**Comment by makkarpov** [comment]
Спасибо.
