### ISSUE TITLE
При установке параметра variable_full_score добавляется параметр score_tokenized

### ISSUE THREAD

**Issue by 977kai** [blackav/ejudge#40]
При установке опции "Allow variable score for full solution?" в YES (конфигурационный параметр
variable_full_score) одновременно в конфигурационный файл добавляется параметр score_tokenized, то есть опция "Score only tokenized submits?" автоматом устанавливается в YES. Соответственно, с этой опцией для обычного контеста в таблице результатов ничего не отображается, ни автоматически, ни вручную заданный баллы за задачу

Приходится вручную в файле serve.cfg удалять параметр score_tokenized. После этого в итоговой таблице результатов отображаются установленные вручную баллы и подсчитывается итог.

**Comment by blackav** [comment]
Fixed 7cad4b60fe8bc91ac3270118f275ad3f3c925310
