### ISSUE TITLE
uldb_plugin_xml.c:set_user_info_field_func: странный неверно работающий код

### ISSUE THREAD

**Issue by batuzovk** [blackav/ejudge#43]
В функции set_user_info_field_func в файле uldb_plugin_xml.c происходит что-то не то.

Функция дожна менять значение одного из полей профиля пользователя. При этом есть два случая: либо меняется базовый профиль, либо меняется профиль в одном из контестов. Соответственно функция находит нужное поле двумя if-ами: в строках 2147 и 2151.

Проблема в том, что между этими if-ами, она уже пытается использовать значение в строке 2149, чтобы проверить, не совпадает ли уже записываемое значение с имеющимся. Чтобы проверка работала, в строку 2148 добавлен код, который безусловно находит поле в профиле внутри контеста, перетирая информацию из предыдущего if-а.

Это приводит к тому, что при редактировании базового профиля через ejudge-edit-users, в последующую функцию userlist_set_user_info_field_str попадает NULL и срабатывает assert:

2018-09-19T09:20:52Z:2:emerg:Internal: userlist.c: 810: assertion failed: ui

Если я правильно понял, что должна делать эта функция и как, то для исправления необходимо удалить строку 2147 и перенести строку 2148 вниз после if-а.

После этого, правда, остается вопрос, может ли быть contest_id < 0? Обрабатываются только случай contest_id >= 0.

https://github.com/blackav/ejudge/blob/25f11633eea9615c1b6057858a25d8e06dba70cc/uldb_plugin_xml.c#L2147-L2156

**Comment by blackav** [comment]
Fixed by e453387a937d78b2cef033565368c73ee1058411
