### ISSUE TITLE
Компиляция под отдельным пользователем [RFI] [УЯЗВИМОСТЬ]

### ISSUE THREAD

**Issue by sleirsgoevy** [blackav/ejudge#45]
Компилировать под основным пользователем опасно, так как с помощью директив `#include` и `.incbin` вредоносный код может прочитать любые файлы системы, в том числе настройки задач, тесты и логи ejudge, содержащие админские куки. Компиляцию следует производить под отдельным пользователем или в песочнице.

**Comment by blackav** [comment]
Fixed in v3.7.9
