### ISSUE TITLE
Дробные оценки и собственные баллы за тест

### ISSUE THREAD

**Issue by solomax2014** [blackav/ejudge#5]
Будет ли в следующих версиях ejudge поддержка дробной оценки за тесты? Т.к. например за задачу максимальный балл нужен 10-20, но тестов 50-100.  (Точность до сотых-тысячных)
+ возможность опционального проставления собственных баллов за тест (например 0 баллов за претесты/тесты из условия, и своё количество баллов за следующие тесты (по 1 баллу, по 1.5, в зависимости от сложности теста или по другим идеям)

**Comment by blackav** [comment]
Дробные баллы вряд ли будут.

Собственные баллы за тест поддерживаются.

**Comment by solomax2014** [comment]
Спасибо за ответ. Закрываю issue.
