### ISSUE TITLE
Отображение кавычек в таблице результатов

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#50]
Если данные пользователя содержат кавычки, то в таблице результатов данные этого пользователя отображаются примерно так:

Лицей &amp;quot;Вторая школа&amp;quot; 8 кл.

**Comment by blackav** [comment]
Кажется, что все ок.

![image](https://user-images.githubusercontent.com/5577025/221340968-19e7be34-350c-4d56-9eaf-75c0cc83500b.png)

![image](https://user-images.githubusercontent.com/5577025/221340990-a8facb83-92f8-4081-a2dc-35ee1dc48c98.png)
