### ISSUE TITLE
Invalid JSON is received on action=problem-status-json

### ISSUE THREAD

**Issue by sleirsgoevy** [blackav/ejudge#55]
`{
  "ok" : true,
  "result": {
    "server_time": 1560716114,
    "problem": {
      "id": 1,
      "short_name": "A",
      "long_name": "Олимпиада",
      "type": 0,
      "full_score": 100,
      "use_stdin": true,
      "use_stdout": true,
      "combined_stdin": true,
      "combined_stdout": true,
      "team_enable_rep_view": true,
      "team_enable_ce_view": true,
      "ignore_compile_errors": true,
      "real_time_limit_ms": 5000,
      "time_limit_ms": 2000,
      "test_score": 1,
      "run_penalty": 0,
      "disqualified_penalty": 1,
      "input_file": input.txt,
      "output_file": output.txt,
      "enable_max_stack_size": true,
      "max_vm_size": "268435456",
      "max_stack_size": "268435456",
      "is_statement_avaiable": true,
      "est_stmt_size": 4096
    },
    "problem_status": {
      "is_viewable" : true,
      "is_submittable" : false,
      "is_tabable" : true,
      "is_solved" : true,
      "best_run" : 6530,
      "best_score" : 100,
      "all_attempts" : 1,
      "eff_attempts" : 1
    }
  }
}
`
The offending lines are lines 23 and 24:
`      "input_file": input.txt,
      "output_file": output.txt,
`

**Comment by blackav** [comment]
fixed 4e6d469dbb85617463d39c3e0e301240dbddb7b3
