### ISSUE TITLE
Master может создать слишком большой clar, что приводит к недоступности турнира

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#57]
Пользователь с правами master в контесте написал комментарий к коду размером 81788 байт через интерфейс master. Система позволила написать ему такой большой комментарий, и внесла его в базу. Кажется, только в таблицу clars, но не в таблицу clartexts.

Потом контест выгрузился. При попытке загрузить этот контест получались следующие ошибки:

Contest is not available
The contest is temporarily not available. Please, retry the request a bit later.

Additional information about this error:

2019-08-12T06:54:33Z:info:loading contest 36513 configuration file
2019-08-12T06:54:33Z:info:configuration file parsed ok
mysql: SELECT config_val FROM config WHERE config_key = 'run_version' ;
mysql: SELECT * FROM runheaders WHERE contest_id = 36513 ; 
mysql: SELECT * FROM runs WHERE contest_id=36513 ORDER BY run_id ;
mysql: SELECT config_val FROM config WHERE config_key = 'clar_version' ;
mysql: SELECT * FROM clars WHERE contest_id=36513 ORDER BY clar_id;
2019-08-12T06:54:33Z:error:database error: invalid value of field size

Для исправления ошибки пришлось исправлять записи в базе MySQL.

**Comment by blackav** [comment]
fixed in a95f3955570a86e70c257e89f0d7253a049007c3
