### ISSUE TITLE
Удалить необходимость нажимать на кнопку "Создать учётную запись" для начала регистрации

### ISSUE THREAD

**Issue by CrafterKolyan** [blackav/ejudge#58]
В интернете уже давным давно при нажатии на кнопку "Регистрация" сразу открывается страница создания новой учётной записи.

В Ejudge реализована крайне неочевидная система, когда необходимо нажать на "Регистрацию", а после этого на "Создать учётную запись". Ещё в 8 классе я столкнулся с этой крайней неочевидностью Ejudge и за всю мою жизнь это была единственная платформа, где мне понадобилось читать гайд как зарегистрироваться, что явно показывает неочевидность данного интерфейса.

Прошу переработать интерфейс, так чтобы нажатие на кнопку "Регистрация" сразу перенаправляло к странице создания учётной записи.

**Comment by blackav** [comment]
<contest id="auto"
         force_registration="yes"
         ...
