### ISSUE TITLE
Неправильные права доступа на каталоги компиляции 

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#59]
Если включена компиляция под отдельным пользователем, то новые каталоги для обмена данными с компиляцией создаются с такими правами:

$ ls -l
итого 12
drwxr-sr-x 2 ejudge ejcompile 4096 окт 17 14:02 dir
drwxr-sr-x 2 ejudge ejcompile 4096 окт 17 14:02 in
drwxr-sr-x 2 ejudge ejcompile 4096 окт 17 14:02 out
$ pwd
/home/judges/compile/var/compile/000942/status

То есть пользователь ejcompile в эти каталоги ничего писать не умеет.
Каталог report аналогично.

**Comment by blackav** [comment]
у меня не воспроизводится:
drwxrwsr-x 4 ejudge ejcompile 4096 Jan  8 21:06 000002
при этом права в compile
drwsrwsr-x 6 ejudge ejcompile 4096 Jan  8 21:06 compile

**Comment by dkirienko** [comment]
Надо будет посмотреть внимательнее, МШП тоже на такое же жаловалось...

**Comment by dkirienko** [comment]
На версии 3.8.0 уже не воспроизводится, по-видимому, было исправлено между 3.7.9 и 3.8.0.

**Comment by dkirienko** [comment]
Нет, всё равно воспроизводится, на вновь созданных контестах.
Если контест был ранее создан, то подкаталоги создаются с правильными правами, а на новых контестах - с неправильными.

**Comment by blackav** [comment]
Не воспроизводится.
Какова точная последовательность действий?

**Comment by blackav** [comment]
старый баг, закрою
