### ISSUE TITLE
Strip ejudge binaries by default

### ISSUE THREAD

**Issue by sleirsgoevy** [blackav/ejudge#64]
In the default configuration, ejudge binaries are built unoptimized with debug symbols. This allows a potential attacker with local shell access (e.g. due to a kernel bug, or to secure_run/suid_run being improperly configured) to **easily** get administrative acccess (serve-control), for example by hooking `passwd_check` in ej-users with gdb. If the binaries were optimized and stripped it would require much more effort (e.g. replacing the binaries with backdoored ones or manually tweaking the database).

**Comment by blackav** [comment]
not a bug
