### ISSUE TITLE
Бесконечный running на языке mcs в задаче с потестовой компиляцией

### ISSUE THREAD

**Issue by IlyaCk** [blackav/ejudge#65]
Если делать задачу с потестовой компиляцией для языка mcs, компиляция, вроде бы проходит нормально (в /home/judges/var/ej-compile.log появляются строки ...:info:Compilation sucessful соответственно количеству тестов), но потом начинается вечный running, в /home/judges/var/ej-super-run.log появляется ...:emerg:Internal: unix/fileutl.c: 463: assertion failed: buf и слетает процесс ej-super-run

Строка 463 файла fileutl.c -- это 
  ASSERT(buf);
который вызывается в самом начале тела функции
int
generic_write_file(char const *buf, size_t size, int flags,
                   char const *dir, char const *name, char const *sfx)

Проблема не_возникает при на mcs без постестовой компиляции, ни при потестовой компиляции на g++.

Всё указанное воспроизводится на ejudge 3.7.9 #1 , а также на ejudge 3.7.6+ из виртуальной машины Fedora-26-32-ejudge-20180322.ova с сайта ejudge.ru

**Comment by blackav** [comment]
Fix 325fd415d6b55156bdecbd2e8bf4494654132a03
