### ISSUE TITLE
Ejudge раскрывает часть информации о закрытых тестах

### ISSUE THREAD

**Issue by MikailBag** [blackav/ejudge#66]
Ejudge поддерживает опцию [separate_user_score](https://ejudge.ru/wiki/index.php/Serve.cfg:global:separate_user_score) в настройках турнира. При установке `open_tests` в конфиге задачи это позволяет полностью убрать упоминание о некоторых тестах из протокола проверки. Однако в текущий момент существует небольшая утечка информации о закрытых тестах.
А именно, система не показывает результат проверки до тех пор, пока тестирование не завершено полностью. Таким образом, недобросовестный участник узнает астрономическое время проверки на всех тестах, в том числе скрытых. Зная также  процессорное время тестирования на нескрытых тестах, можно предположить суммарное время исполнения на скрытых. Из этого можно делать определенные выводы. Например, если мы знаем что в одной из скрытых групп 20 тестов, ограничение по времени 1 секунда, а тестирование на скрытых тестах шло больше 20 секунд, то наверное эта группа была пройдена.

**Comment by blackav** [comment]
не очень понятно, что с этим делать

**Comment by sleirsgoevy** [comment]
Наверное, можно сделать в БД отдельные поля a la "статус для участника", и заполнять их, как только завершено тестирование на открытых тестах. Тогда участник увидит результат до фактического окончания тестирования и не сможет ничего измерить.

**Comment by blackav** [comment]
Как только в очереди посылок будет больше одной посылки что-либо понять уже будет невозможно.

**Comment by sleirsgoevy** [comment]
Если очередь обрабатывается в порядке отправки, можно отослать две посылки подряд и измерить время между окончанием тестирования первой и второй. Так что вполне возможно.

**Comment by blackav** [comment]
не стоит усилий на "исправление"
