### ISSUE TITLE
Ошибка MYSQL при входе в MASTER

### ISSUE THREAD

**Issue by mezun7** [blackav/ejudge#67]
После обновления системы возникает следующая ошибка:

`2020-04-20T19:46:43Z:info:loading contest 2 configuration file
2020-04-20T19:46:43Z:info:configuration file parsed ok
mysql: SELECT config_val FROM config WHERE config_key = 'run_version' ;
mysql: ALTER TABLE runs ADD COLUMN prob_uuid VARCHAR(40) DEFAULT NULL AFTER token_count
2020-04-20T19:46:44Z:error:database error: Invalid default value for 'create_time'`

**Comment by blackav** [comment]
ничего непонятно. с какой версии обновляли, на какую версию обновляли? какая у вас система? какая БД?

**Comment by dkirienko** [comment]
Похоже на мои проблемы с запуском на MySQL после обновление до 3.8.

Лечилось ручной правкой базы данных. Запросы вида:

alter table runs change last_change_time last_change_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, change create_time create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

Сделать так нужно в таблице runs и в других таблицах, где у полей типа timestamp стоит значение по умолчанию нулевым.

**Comment by mezun7** [comment]
> ничего непонятно. с какой версии обновляли, на какую версию обновляли? какая у вас система? какая БД?

Ubuntu 16.04
БД Mysql 5.7
Версия была 3.7. Переходили в 3.8.

**Comment by blackav** [comment]
fixed e7fd72fcdd9114b8de3c13ce9b0b8b0374ed0d2e
