### ISSUE TITLE
API ejudge

### ISSUE THREAD

**Issue by Hedgehogues** [blackav/ejudge#68]
Привет. Есть ли дока к API ejudge? Видел, что API появилась в последней версии. 

От проверяющей системы мне нужна только песочница. Возможно ли её использовать отдельно, либо же через API? Как это лучше сделать?

**Comment by sleirsgoevy** [comment]
Вот [тут](http://www.ejudge.ru/wiki/index.php/%D0%9F%D0%B0%D1%82%D1%87_%D0%BA_%D1%8F%D0%B4%D1%80%D1%83_Linux:_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) расписано, как пользоваться песочницей из еджепатча. Ну лучше использовать нормальную песочницу, не требующую патча ядра, например firejail или [minion](https://github.com/jjs-dev/minion).

//Немного самопиара в issues чужой репы: https://github.com/sleirsgoevy/jjs-kvm . Проект кастомного ядра только для запуска посылок участников.
