### ISSUE TITLE
Плохая вёрстка страницы просмотра регистрационной информации в мобильных браузерах

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#69]
Скриншот. Подробности браузера неизвестны. Не удаётся нажать на кнопку "Участвовать" в итоге.

![image](https://user-images.githubusercontent.com/12986040/83234308-b9a63580-a198-11ea-9f63-dcc87826e6df.png)

UPD: Скриншот, вероятно, сделан на устройстве "Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-A307FN) AppleWebKit/537.36 (KHTML, like Gecko) **SamsungBrowser/11.1** Chrome/75.0.3770.143 Mobile Safari/537.36"

**Comment by dkirienko** [comment]
Вот ещё скриншот.
![image](https://user-images.githubusercontent.com/12986040/83231190-c70cf100-a193-11ea-8e4b-bbf5c1bd3271.png)

Кажется, это называется "Mozilla/5.0 (Linux; Android 7.0; **SAMSUNG SM-A310F Build/NRD90M**) AppleWebKit/537.36 (KHTML, like Gecko) **SamsungBrowser/9.2** Chrome/67.0.3396.87 Mobile Safari/537.36"

**Comment by dkirienko** [comment]
Поставил Samsung Browser на свой Huawei-планшет, судя по внешнему виду кнопок - это, действительно, Samsung Browser, но у меня проблем с отображением нет. Правда, мой браузер идентифицируется как

"Mozilla/5.0 (Linux; Android 7.0; BTV-DL09) AppleWebKit/537.36 (KHTML, like Gecko) **SamsungBrowser/11.2** Chrome/75.0.3770.143 Mobile Safari/537.36"

**Comment by blackav** [comment]
старый баг
