### ISSUE TITLE
Setrlimit on child process

### ISSUE THREAD

**Issue by laplab** [blackav/ejudge#7]
In file `reuse_exec.c` declaration of `task_Start` is unsafe. As described [here](http://stackoverflow.com/q/5784595/4878284) child process can change limit by calling `setrlimit`. This can cause cancelling limitations that are in the task statement

**Comment by blackav** [comment]
with special linux kernel patch all insecure system calls are disabled for the child process (see 'enable_secure_exec';
also necessary restrictions may be enforced by the suid helper program (see 'enable_suid_exec')

**Comment by laplab** [comment]
Is it needed though?
Child process cannot raise hard limits of setrlimit without CAP_SYS_RESOURCE so cancelling this capability will do the trick
