### ISSUE TITLE
Если решение участника не считывает вывод интерактора, процесс блокируется

### ISSUE THREAD

**Issue by pavel-the-best** [blackav/ejudge#73]
Бывают ситуации, когда решению участника не нужно считывать оставшийся вывод интерактора, поэтому оно его не считывает для экономии времени исполнения.
Но когда вывод интерактора становится больше максимального размера pipe, при следующей попытки записи процесс интерактора блокируется, что приводит к превышению лимита реального времени.
Для решения этой проблемы достаточно задавать большой максимальный размер pipe (это можно сделать с помощью `F_SETPIPE_SZ`) в интерактивных задачах.
Ещё одно возможное решение: модифицировать testlib так, что если решение участника завершилось, нужно разблокировать интерактор и игнорировать дальнейший его вывод.

**Comment by blackav** [comment]
Баг в интеракторе

**Comment by pavel-the-best** [comment]
А как можно написать интерактор без этого бага?

**Comment by blackav** [comment]
Например, развести запись и чтение по разным тредам. Но возможно, специфика задачи может позволять и другое решение.
