### ISSUE TITLE
ПРОБЛЕМА РЕШЕНА! Патч к ядру 4.9.158 (и патч к ядру 5.4.42) не работает с дистрибутивом Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by 977kai** [blackav/ejudge#77]
Версия ejudge 3.8.0. 
Дистрибутив Ubuntu 20.04 LTS

Патч к ядру 4.9.158
Пробовал также самостоятельно сделанный патч ядру 5.4.42 

При выполнении кода на С++ в режиме Run programs securely выпадает ошибка

--- Stderr: size 128 ---
./000887: error while loading shared libraries: /lib/x86_64-linux-gnu/libc.so.6: cannot read file data: Operation not permitted

В патч к ядру 5.4.42, кроме других изменений, добавил в массив  secure_paths[]  пути "/usr/local/lib/x86_64-linux-gnu/", "/lib/x86_64-linux-gnu/",  "/usr/lib/x86_64-linux-gnu/", но это не помогло.

Если режим безопасности отключить, все работает нормально
Код на других языках (fpc, python3, java, assembler) компилируется и исполняется нормально.

**Comment by 977kai** [comment]
Проблема состояла вот в чем. Для того, чтобы shared objects подключались динамически, в настройках языка программирования должно быть установлено значение параметра Language architecture:  linux-shared

У меня в некоторых контестах этой настройки почему-то не было. На пропатченном ядре 4.9.158 и с предыдущим дистрибутивом Ubuntu все работало. После обновления дистрибутива - перестало. Ядро было после обновления 5.4.0-42.

Я сделал патч к ядру 5.4.42, попытавшись разобраться в патче 4.9.158. В пятом ядре появилась новая директория /lib/x86_64-linux-gnu/ в которой лежат теперь динамические библиотеки, в частности libc.so.6. Я ее добавил в массив безопасных директорий (и в /usr/lib/ тоже). Кое-где пришлось поменять немного добавляемый в системные вызовы код патча, так как код этих системных вызовов немного поменялся. Не уверен, что я все сделал до конца правильно, но пока у меня машина и ejudge работают на этом пропатченом ядре 5.4.42.

Поменять настройку Language architecture удалось только вручную прямо в файле serve.cfg Почему-то в web-интерфейсе для настройки опций языков программирования Language settings  вот эти пункты в созданных ранее контестах

Language ID:
Language compile ID:
Language short name:
Language architecture:
Suffix of the source files:
Suffix of the executable files:

поменять невозможно, они как будто заблокированы для редактирования. Может быть, при создании нового контеста они будут работать, не пробовал пока. 

Если патч 5.4.42 нужен, дайте знать. Даже если там не все правильно, часть работы уже сделана, может пригодится.

**Comment by sleirsgoevy** [comment]
Патч нужен. Например для защиты от [этой уязвимости](https://bugs.chromium.org/p/project-zero/issues/detail?id=1903), исправленной в 5.2.

**Comment by 977kai** [comment]
Было бы очень здорово, если бы кто-нибудь еще разок этот патч проверил и, возможно, дополнил. Я не уверен до конца, что не ошибся где-нибудь, хотя пока все работает на ядре 5.4.42 с этим патчем без сбоев.

[patch_5.4.42.tar.gz](https://github.com/blackav/ejudge/files/5170129/patch_5.4.42.tar.gz)
