### ISSUE TITLE
Доступ к интернету у тестируемых программ

### ISSUE THREAD

**Issue by anonymix007** [blackav/ejudge#78]
Есть ли по умолчанию доступ к интернету у тестируемых программ? Можно ли его дать?

**Comment by sleirsgoevy** [comment]
Единственный способ "дать интернет" — отключить безопасное выполнение для задачи (оно по умолчанию отключено для таких языков как Pascal.ABC и C#). Но это чревато.

А еджаджу бы следовало активировать network namespace при работе на достаточно свежем ядре. Чтобы хотя бы «сливов» не было.

**Comment by anonymix007** [comment]
То есть у Pascal.ABC и C# по умолчанию есть доступ к интернету?

**Comment by sleirsgoevy** [comment]
Да. Но IMHO это баг а не фича.

**Comment by anonymix007** [comment]
К чему, например?

**Comment by blackav** [comment]
Эти языки отмечены как insecure, то есть никаких вообще ограничений на них нет.
