### ISSUE TITLE
Не поддерживается запуск kotlin-программ, где главный метод определен в классе.

### ISSUE THREAD

**Issue by ov7a** [blackav/ejudge#82]
Это происходит из-за того, что там отсутствует манифест.
Т.е. такая программа
```kotlin
fun main(args: Array<String>) {
    println("Hello, World!")
}
```
Будет успешно скопилирована, т.к. манифест генерируется компилятором котлина автоматически.

А вот такая - уже нет
```kotlin
object Main {
  @JvmStatic
  fun main(args: Array<String>) {
    println("Hello, World!")
  }
}
```
по причине `no main manifest attribute, in ./Main.jar`. Почему не генерируется манифест можно посмотреть в [исходниках компилятора](https://github.com/JetBrains/kotlin/blob/master/compiler/frontend/src/org/jetbrains/kotlin/idea/MainFunctionDetector.kt). Есть [открытый баг](https://youtrack.jetbrains.com/issue/KT-32376).
Для java эта проблема решается переупаковой jar с поиском манифеста - за это отвечает [ej-javac](https://github.com/blackav/ejudge/blob/master/extra/ej-javac.c). А для котлина в ejudge такого нет.

**Comment by blackav** [comment]
баг в котлине закрыт
