### ISSUE TITLE
Неправильная обработка пустого значения при выборе класса (уровня обучения) в регистрационной анкете

### ISSUE THREAD

**Issue by dkirienko** [blackav/ejudge#83]
Код поля выбора регистрационной анкеты генерируется в new_server_html_5.c
функция display_grade_changing_dialog

Там такой код:
```
  for (n = -1; n < 12; n++) {
    sel = "";
    if (n == val) sel = " selected=\"selected\"";
    if (n == -1) {
      s1 = s2 = "";
    } else if (!n) {
      continue;
    } else {
      snprintf(buf, sizeof(buf), "%d", n);
      s1 = s2 = buf;
    }
    fprintf(fout, "<option value=\"%s\"%s>%s</option>", s1, sel, s2);

```
Он генерирует такой HTML.

`<select name="mparam_9"><option value=""></option><option value="0" selected="selected">Прочее</option><option value="1">1</option>`

Здесь невыбранное значение соответствует пустой строке.

Однако потом при парсинге этой анкеты это значение превращается в число 0. По-видимому (не уверен), это происходит в этом же файле в функции get_member_field

В общем, если пользователь не выберет ничего в этом поле, то оно примет значение 0, а это считается корректным выбором, соответствующим "Прочее".

В файле userlist.c есть функция userlist_is_empty_member_field:

  ```
case USERLIST_NM_GRADE:
    p_int = (const int*) userlist_get_member_field_ptr(m, field_id);
    return (*p_int < 0);
```

И вот в этой функцией некорректным (пустым) значением считается grade < 0.

По-видимому предполагалось, что если поле grade не заполнено, то оно должно быть равно -1, но оно оказывается равно 0, что является ошибкой.

**Comment by blackav** [comment]
fixed in 0860f82a65639dde9d7fd7beb6035ba50b2833e0
