### ISSUE TITLE
group is a reserved keyword in mysql

### ISSUE THREAD

**Issue by CosmoRied** [blackav/ejudge#88]
Hi, installation of ejudge on my system caused an error when installing the database. it seems that the table 'groups' violates a new reserved keyword in mysql 8.2... [reserved keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#:~:text=GRANTS-,GROUP,-(R))

with error, 

`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (     group_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,     grou' at line 1
mysql> create table groups;
`

You can fix this by surrounding in **backticks** `` or capitalising Groups, but I can't find sql script to alter this specifically. Re-installing after manually adding Group by sql is overwritten by program option:

> This script will ERASE the exising user database and contests!
Are you sure to proceed (yes/no)?

Great, so what now?

[Issue in mysql ](https://github.com/concrete5/concrete5/issues/6156)

**Comment by blackav** [comment]
Fixed in v3.9.0
