### ISSUE TITLE
segfolt скрипта ejudge-setup на debian 11

### ISSUE THREAD

**Issue by ilyapashuk** [blackav/ejudge#90]
здравствуйте.

собираю ejudge на debian 11.

для успешной отработки make в несколько makefiles пришлось дописать:
-Xlinker --allow-multiple-definition
в ldflags.

сборка отработала нормально, но при запуске ./ejudge-setup на этапе save install script происходит segfolt, никаких сообщений об ошибках перед этим не выдаётся.

как заставить скрипт работать или обойти его, выполнив вручную совершаемые им действия?

**Comment by blackav** [comment]
Какая версия ejudge?

**Comment by ilyapashuk** [comment]
версия 3.8.0, исходник взят по ссылке с главной страницы.

теперь разобрался, в чём причина.

когда подготавливал зависимости к сборке, не стал ставить sendmail, поскольку разворачивал локально на виртуалке и настраивать ещё и элпочту не собирался.

далее скрипт ejudge-setup на этапе settings variables validation обнаруживает, что sendmail нет, и вероятно хочет выдать сообщение об ошибке через ncurses.

далее, похоже, начинается какое-то некорректное взаимодействие с этим ncurses, что и приводит к сегфолту без вменяемого объяснения причины.

тут либо api ncurses разошлось с тем, с которым работали вы, потому что разные версии, либо у вас где-то в коде ошибка.

после установки sendmail всё отработало нормально.

тем не менее, issue не закрываю, поскольку очевидно, что программа в данной ситуации должна вести себя несколько иначе.

кроме того, имели место многочисленные сегфолты при попытке внесения изменений в различные опции, доступные в том меню, например, при попытке отключить mysql, так что пришлось править дефолтные значения напрямую в коде.

с другой стороны, возможно, это на моей стороне что-то не то, сборка ведь осуществляется под официально неподдерживаемый дистр.

я достаточно разбираюсь в программировании, чтобы понимать, что вами проделана огромная, грандиозная работа, которая, несомненно, достойна благодарности, но, извините, у вас никогда не возникало в процессе разработки сомнений в том, что голый C действительно подходит подобного рода софту?

ну ещё с тем процессом, который собственно делает контролируемый запуск кода, это, может, и обосновано, а вот с другими?
