### ISSUE TITLE
Обработать тестлибовский вердикт _points

### ISSUE THREAD

**Issue by kunyavskiy** [blackav/ejudge#96]
Сейчас задачи с кастомной оценкой выставляемой чекером (scoring_checker) сделаны достаточно неудобно, а именно, нужно каким-то образом стандартные тестлибовские ошибки возвращающие WA превращать в PE. Да и просто использование WA в качестве partially correct это костыль. 

В тестлибе для этого есть отдельный exit code points. Было бы хорошо поддержать. Сейчас в полигоне есть два режима интерпретации, выбор из которых является настройкой задачи. Возвращенное число это или абсолютное значение скора, или процент от максимального балла за тест. Было бы хорошо такое тоже поддержать, в том числе в импорте из полигона.

**Comment by blackav** [comment]
В testlib формате есть поддержка частичных баллов за решение, там используется exit code 7, и потом в stdout пишется строка вида "points <балл за тест> <какое-то сообщение чекера>". (Philip Gribov)

**Comment by blackav** [comment]
сообщение в виде points X пишется в stderr. это тупо

**Comment by kunyavskiy** [comment]
У тестлиба есть режим с выводом всей ошибки в файл. Вроде даже в виде xml. Но в любом случае, этот текст захватывается вроде бы как комментарий чекера.
