### ISSUE TITLE
`ej-suid-container` не закрывает `response_fd`

### ISSUE THREAD

**Issue by vovams** [blackav/ejudge#98]
Программа `ej-suid-container` не закрывает файловый дескриптор, предназначенный для возврата результата выполнения (`response_fd`), перед запуском тестируемой программы. В результате тестируемая программа его наследует и может в него писать.

Например, в моей установке отправка следующего кода приводит к вердикту Check failed и отображению ошибки `invalid reply from container: Who's there?` в отчёте:

    #include <unistd.h>
    
    int main() {
        static constexpr char MSG[] = "Who's there?";
        write(4, MSG, sizeof(MSG));
        return 0;
    }

Номер дескриптора был найден с помощью отправки следующего кода:

    #include <iostream>
    #include <unistd.h>
    
    int main() {
        std::cout << "checking..." << std::endl;
        for (int fd = 3; fd < 10240; fd++) {
            if (close(fd) == 0)
                std::cout << fd << std::endl;
        }
        return 0;
    }

**Comment by blackav** [comment]
Fixed in 3.9.1
