### ISSUE TITLE
Отправка email не работает в 3.9.0

### ISSUE THREAD

**Issue by vovams** [blackav/ejudge#99]
Отправка email уведомлений не работает в ejudge 3.9.0. Мне, похоже, удалось разобраться, почему. При выполнении отправки письма программа `ej-jobs` попадает в бесконечный цикл в процессе передачи тела письма на stdin программы `sendmail` и передаёт тело письма бесконечное количество раз. В моём случае в результате программа `sendmail` (из пакета MTA [nullmailer]), видимо, после того, как суммарный размер получившегося письма превышает некоторый лимит, отклоняет письмо и завершается. Бесконечный цикл получается из-за того, что в функции `pipe_write_func()` не обновляется значение `fdi->wr_pos`. Кроме того, это поле нигде не инициализируется.

[nullmailer]: http://untroubled.org/nullmailer/

Также, в функции `run_process()` допущена описка при передаче аргументов в функцию `fdinfo_create()` для создания структуры для чтения stderr запускаемой программы. В результате сообщение об ошибке от `sendmail` не попадало в лог.

Приведённый ниже патч исправляет все три проблемы. У меня с этим патчем, похоже, всё работает.

```
--- a/bin/ej-jobs.c	2021-12-28 08:15:35.000000000 +0200
+++ b/bin/ej-jobs.c	2022-01-27 22:51:18.804296014 +0200
@@ -1626,6 +1626,7 @@
             err("pipe_write_func: write returned 0");
             goto done;
         }
+        fdi->wr_pos += r;
     }
     return;
 
@@ -2143,6 +2144,7 @@
     fdi_stdin = fdinfo_create(as, p0[1], &pipe_ops); p0[1] = -1;
     fdi_stdin->wr_data = xstrdup(stdin_buf);
     fdi_stdin->wr_size = strlen(stdin_buf);
+    fdi_stdin->wr_pos = 0;
     app_state_arm_for_write(as, fdi_stdin);
 
     fdi_stdout = fdinfo_create(as, p1[0], &pipe_ops); p1[0] = -1;
@@ -2150,7 +2152,7 @@
     fdi_stdout->rd_data[0] = 0;
     app_state_arm_for_read(as, fdi_stdout);
 
-    fdi_stderr = fdinfo_create(as, p1[0], &pipe_ops); p1[0] = -1;
+    fdi_stderr = fdinfo_create(as, p2[0], &pipe_ops); p2[0] = -1;
     fdi_stderr->rd_data = xmalloc(fdi_stderr->rd_rsrv = 16);
     fdi_stderr->rd_data[0] = 0;
     app_state_arm_for_read(as, fdi_stderr);
```

**Comment by vovams** [comment]
Поправка: не обратил внимание, что поле `wr_pos` инициализируется функцией выделения памяти `xcalloc()`. Получается, достаточно такого патча:

```
--- a/bin/ej-jobs.c	2021-12-28 08:15:35.000000000 +0200
+++ b/bin/ej-jobs.c	2022-01-28 01:02:56.224048458 +0200
@@ -1626,6 +1626,7 @@
             err("pipe_write_func: write returned 0");
             goto done;
         }
+        fdi->wr_pos += r;
     }
     return;
 
@@ -2150,7 +2151,7 @@
     fdi_stdout->rd_data[0] = 0;
     app_state_arm_for_read(as, fdi_stdout);
 
-    fdi_stderr = fdinfo_create(as, p1[0], &pipe_ops); p1[0] = -1;
+    fdi_stderr = fdinfo_create(as, p2[0], &pipe_ops); p2[0] = -1;
     fdi_stderr->rd_data = xmalloc(fdi_stderr->rd_rsrv = 16);
     fdi_stderr->rd_data[0] = 0;
     app_state_arm_for_read(as, fdi_stderr);
```

**Comment by blackav** [comment]
Fixed in 3.9.1
